version: "3.9"
services:
  web:
    build:
      context: apps/web
      dockerfile: Dockerfile
      target: builder
    command: yarn dev
    env_file: apps/web/.env.local
    image: web
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
      target: builder
    command: yarn dev
    env_file: apps/api/.env
    image: api
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aafiyah
    ports:
      - "5432:5432"
