import RootLayoutWrapper from '../layouts';
import '../styles/global.css';
import { StyledComponentsRegistry } from './registry';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <StyledComponentsRegistry>
          <RootLayoutWrapper>{children}</RootLayoutWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
